export interface Card {
    id: string,
    name: string,
    rarity: string,
    class: string,
    type: string,
    imageURL: ImageLink,
    leaderSkill: string,
    technicalLeaderSkill: LeaderRecap,
    categories: Set<string>,
}

export interface LeaderRecap {
    mainLeaders: Lead[],
    secondaryLeaders: Lead[],
    // alternativeLeaders: Lead[],
}

export interface Lead {
    category: Category,
    ki?: number,
    percentage: number
}

export interface Character {
    name: string,
    title: string,
    maxLevel: number,
    maxSALevel: number,
    rarity: Rarities,
    class: Classes,
    type: Types,
    cost: number,
    id: string,
    imageURL: ImageLink,
    leaderSkill: string,
    ezaLeaderSkill?: string,
    superAttack: string,
    ezaSuperAttack?: string,
    ultraSuperAttack?: string,
    ezaUltraSuperAttack?: string,
    passive: string,
    ezaPassive?: string,
    activeSkill?: string,
    activeSkillCondition?: string,
    ezaActiveSkill?: string,
    ezaActiveSkillCondition?: string,
    transformationCondition?: string,
    links: string[],
    categories: string[],
    kiMeter: string[],
    baseHP: number,
    maxLevelHP: number,
    freeDupeHP: number,
    rainbowHP: number,
    baseAttack: number,
    maxLevelAttack: number,
    freeDupeAttack: number,
    rainbowAttack: number,
    baseDefence: number,
    maxDefence: number,
    freeDupeDefence: number,
    rainbowDefence: number,
    kiMultiplier: string,
    transformations?: Transformation[]
}

export interface ImageLink {
    simpleUrl?: string
    complexeUrl?: string
}
export enum Classes {
    Super = "Super",
    Extreme = "Extreme"
}

export enum Types {
    PHY = "PHY",
    STR = "STR",
    AGL = "AGL",
    TEQ = "TEQ",
    INT = "INT"
}

export enum Rarities {
    UR = "UR",
    LR = "LR",
    UNSUPORTED = "unsuported"
}

export interface Transformation {
    transformedID: string,
    transformedName: string,
    transformedClass: Classes,
    transformedType: Types,
    transformedSuperAttack: string,
    transformedEZASuperAttack?: string,
    transformedUltraSuperAttack?: string,
    transformedEZAUltraSuperAttack?: string,
    transformedPassive: string,
    transformedEZAPassive?: string,
    transformedActiveSkill?: string,
    transformedActiveSkillCondition?: string,
    transformedLinks: string[],
    transformedImageURL: string,
}

export enum Category {
    MovieBosses = 'Movie Bosses',
    JoinedForces = 'Joined Forces',
    BondOfFriendship = 'Bond of Friendship',
    PowerOfWishes = 'Power of Wishes',
    SuperBosses = 'Super Bosses',
    ResurrectedWarriors = 'Resurrected Warriors',
    MajinBuuSaga = 'Majin Buu Saga',
    PureSaiyans = 'Pure Saiyans',
    VegetasFamily = "Vegeta's Family",
    WorthyRivals = 'Worthy Rivals',
    OtherworldWarriors = 'Otherworld Warriors',
    SuperSaiyan2 = 'Super Saiyan 2',
    AllOutStruggle = 'All-Out Struggle',
    ConnectedHope = 'Connected Hope',
    GiftedWarriors = 'Gifted Warriors',
    TimeLimit = 'Time Limit',
    MasteredEvolution = 'Mastered Evolution',
    BattleOfFate = 'Battle of Fate',
    PowerBeyondSuperSaiyan = 'Power Beyond Super Saiyan',
    BondOfParentAndChild = 'Bond of Parent and Child',
    PeppyGals = 'Peppy Gals',
    DragonBallSeekers = 'Dragon Ball Seekers',
    Youth = 'Youth',
    DBSaga = 'DB Saga',
    Earthlings = 'Earthlings',
    EarthBredFighters = 'Earth-Bred Fighters',
    FullPower = 'Full Power',
    GokusFamily = "Goku's Family",
    Kamehameha = 'Kamehameha',
    FinalTrumpCard = 'Final Trump Card',
    TurtleSchool = 'Turtle School',
    RealmOfGods = 'Realm of Gods',
    Potara = 'Potara',
    FutureSaga = 'Future Saga',
    TimeTravelers = 'Time Travelers',
    BattleOfWits = 'Battle of Wits',
    AcceleratedBattle = 'Accelerated Battle',
    FusedFighters = 'Fused Fighters',
    SuperHeroes = 'Super Heroes',
    HybridSaiyans = 'Hybrid Saiyans',
    MovieHeroes = 'Movie Heroes',
    SiblingsBond = "Siblings' Bond",
    SuperSaiyans = 'Super Saiyans',
    Saviors = 'Saviors',
    DefendersOfJustice = 'Defenders of Justice',
    TransformationBoost = 'Transformation Boost',
    BondOfMasterAndDisciple = 'Bond of Master and Disciple',
    Revenge = 'Revenge',
    EntrustedWill = 'Entrusted Will',
    ShadowDragonSaga = 'Shadow Dragon Saga',
    GiantApePower = 'Giant Ape Power',
    GTHeroes = 'GT Heroes',
    ExplodingRage = 'Exploding Rage',
    MiraculousAwakening = 'Miraculous Awakening',
    RapidGrowth = 'Rapid Growth',
    HeavenlyEvents = 'Heavenly Events',
    TournamentParticipants = 'Tournament Participants',
    SaiyanSaga = 'Saiyan Saga',
    UniverseSurvivalSaga = 'Universe Survival Saga',
    RepresentativesOfUniverse7 = 'Representatives of Universe 7',
    PowerfulComeback = 'Powerful Comeback',
    CorrodedBodyAndMind = 'Corroded Body and Mind',
    UncontrollablePower = 'Uncontrollable Power',
    SpecialPose = 'Special Pose',
    TargetGoku = 'Target: Goku',
    SwornEnemies = 'Sworn Enemies',
    Namekians = 'Namekians',
    PlanetaryDestruction = 'Planetary Destruction',
    Fusion = 'Fusion',
    WorldTournament = 'World Tournament',
    Androids = 'Androids',
    ArtificialLifeForms = 'Artificial Life Forms',
    InhumanDeeds = 'Inhuman Deeds',
    PowerAbsorption = 'Power Absorption',
    GTBosses = 'GT Bosses',
    WickedBloodline = 'Wicked Bloodline',
    TerrifyingConquerors = 'Terrifying Conquerors',
    WorldwideChaos = 'Worldwide Chaos',
    LowClassWarrior = 'Low-Class Warrior',
    TeamBardock = 'Team Bardock',
    SpaceTravelingWarriors = 'Space-Traveling Warriors',
    StoriedFigures = 'Storied Figures',
    MajinPower = 'Majin Power',
    PlanetNamekSaga = 'Planet Namek Saga',
    GiantForm = 'Giant Form',
    Crossover = 'Crossover',
    LegendaryExistence = 'Legendary Existence',
    GinyuForce = 'Ginyu Force',
    SuperSaiyan3 = 'Super Saiyan 3',
    Universe11 = 'Universe 11',
    Universe6 = 'Universe 6',
    DragonBallHeroes = 'Dragon Ball Heroes',
    FusedFighter = 'Fused Fighter',
    AndroidsCellSaga = 'Androids-Cell Saga',
    Super = "Super Class",
    Extreme = "Extreme Class",
    Unsuported = "Unsuported"
}